version: '3'

services:
  octopush:
    build: .
    volumes:
      - ./:/home/node
    ports:
      - 3000:3000

  postgres:
    image: postgres:11-alpine
    ports:
      - 5444:5432
    environment:
      - POSTGRES_DB=octopush
      - POSTGRES_USER=octopush
      - POSTGRES_PASSWORD=octopush
